Add jumping cheat and prevent invincible from allowing the health bar to go in red
ZeikJT/CrossCodeCheats pull request #4
Opened 2021-08-09 23:17 UTC by grasmanek94

2021-09-01 00:27 UTC, ZeikJT commented on cheats.js
> +	var a = Vec2.create(), d = {};
These variable names a,d are too generic and don't seem to be used below?

2021-09-01 00:28 UTC, ZeikJT commented on cheats.js
> +		},
Indentation here seems to be all over the place.

2021-09-01 00:30 UTC, ZeikJT commented on cheats.js
> +	["jumpfurther",             {defaultValue: 10,   type: "SLIDER", min: 10, max: 40,requires: ["jumphigher"]}],
Missing a space between the comma and requires.

2021-09-01 00:30 UTC, ZeikJT commented on cheats.js
> +	["runspeedmultiplier",      {defaultValue: 10,   type: "SLIDER", min: 1, max: 100,requires: ["runspeed"]}],
Same as above, missing a space between the comma and requires.

2021-09-01 00:31 UTC, ZeikJT requested changes
Overall these seem like really cool additions! Thanks for working on adding them :)

2021-09-02 12:23 UTC, grasmanek94 commented
> Overall these seem like really cool additions! Thanks for working on adding them :)

Yeah most of these I had already modded myself into the compiled game.js, I ported them here :)

2021-09-07 06:40 UTC, merged